create view newschool_profile as (SELECT newschool_details.temp_id AS emis_user_id,1 AS emis_usertype,0 AS emis_usertype1,udise_code AS emis_username,
emis_password,ref,'Active' AS status,DATE(NOW()) AS login_date,0 AS login_attempt,0 AS temp_log,0 AS temp_log1,
newschool_details.temp_id AS school_id,udise_code,school_name,manage_cate_id,sch_management_id,sch_directorate_id,
district_id,edu_dist_id,block_id,
(SELECT district_name FROM schoolnew_district WHERE id=district_id) AS district_name,
(SELECT edn_dist_name FROM schoolnew_edn_dist_mas WHERE id=edu_dist_id) AS edn_dist_name,
(SELECT block_name FROM schoolnew_block WHERE id=block_id) AS block_name,
(SELECT manage_name FROM schoolnew_manage_cate WHERE id=manage_cate_id) AS management,
(SELECT category_name FROM schoolnew_type WHERE id=schoolcat) AS cate_type,
urbanrural,
local_body_type_id AS local_body_id,village_panchayat_id AS lb_vill_town_muni,vill_habitation_id AS lb_habitation_id,
assembly_id,parliament_id,pincode,email AS sch_email,website,school_landline AS office_landline,corr_hm_landline AS corr_landlline,
mobile AS office_mobile,corr_hm_mobile AS corr_mobile,1 AS curr_stat,schooltype AS school_type,schoolcat AS scl_category,
low_class,high_class,
newschool_details.temp_id AS school_key_id,totland_sq AS land_avail_sqft,totland_acre,schoolfaci AS land_exp_scl,expan_sq AS play_land_area,
playgroundfacil AS play_facility,playground_sq AS play_area_sqft,playground_acre,alterarrange AS play_alt_arrang,
alter_address AS play_address,dist_bg AS dist_build_playgr,landowner AS land_ownersip,land_amount AS land_rent_amt,
period_lease AS land_lease_perid,lease_date,wall_type AS cmpwall_type,peri_bound AS cmpwall_perimtr, 
land_bound AS cmpwall_length,total_block AS build_block_no,class_und_con AS classrm_undr_constr,
desk AS classrm_desk_studs,ramp AS ramp_disable_child,handrails AS ramp_handrail,staffquater AS staffquarter,
quater_room AS rooms_staffquartrs,gent_toil_staff AS toil_gents_tot,ladie_toil_staff AS toil_ladies_tot,
gent_uri_staff AS urinal_gents_tot,ladie_uri_staff AS urinals_tot_ladies,tot_inuse_boys AS toil_bys_inuse,
tot_notuse_boys AS toil_notuse_bys, 
reason_notuse_boys AS toil_nonfunc_bys,
tot_inuse_girls AS toil_inuse_grls, 
tot_notuse_girls AS toil_notuse_grls,reason_notuse_girls AS toil_reasn_grls,cswn_inuse_boys AS cwsntoil_inuse_bys,
cswn_notuse_boys AS cwsntoil_notuse_bys,cwsn_reasonnotuse_boys AS cwsntoil_reasn_bys,cwsn_inuse_girls AS cwsntoil_inuse_grls,
cwsn_notuse_girls AS cwsntoil_notuse_grls,cwsn_reasonnotuse_girls AS cwsntoil_reasn_grls,urinals_inuse_boys AS urinls_inuse_bys,
urinals_notuse_boys AS urinls_notuse_bys,urinal_reasonnotuse_boys AS urinls_reasn_bys,urinals_inuse_girls AS urinls_inuse_grls,
urinals_notuse_girls AS urinls_notuse_grls,urinal_reasonnotuse_girls AS urinls_reasn_grls,toi_flush_boys AS toil_waterfac_bys,
toi_flush_girls AS toil_waterfac_grls,sanitory AS toil_sanit_wrks,additional_toilet AS toil_land_avail,
additional_sqft AS toil_land_avail_sqft,incen AS incinerator,func_choolas AS inc_auto_avail,nonfunc_choolas AS inci_auto_func_no,
func_auto AS inci_man_avail_no,nonfunc_auto AS inci_man_func_no,tot_tap_avail AS tot_handwash_bys,
tot_tap_func AS tot_handwash_grls,schooltank AS overheadtank_avail,waterpurifier AS waterpuri_avail,
rainwater AS schl_rainwtr_hrv,drinkingwater AS drnkwater_avail,drink_water AS drnkwater_source,
other_drinkwater AS drnkwater_othsource,wellclose AS well_top
FROM newschool_details join newschool_detailsland on newschool_detailsland.temp_id=newschool_details.temp_id);